// MIT License — Piano Learning App
// Hardcoded song library. Each song has notes [{note, duration, start}] in
// beats (quarter note = 1 beat). The song player hook converts beats to
// seconds using the song's BPM and the user's tempo multiplier.

import type { Song } from "@/types";

export const SONGS: Song[] = [
  {
    id: "twinkle",
    title: "Twinkle Twinkle Little Star",
    artist: "Traditional",
    bpm: 100,
    difficulty: "Beginner",
    description: "The classic nursery rhyme. Great first song.",
    notes: [
      // Phrase 1: Twinkle, twinkle, little star
      { note: "C4", duration: 1, start: 0 },
      { note: "C4", duration: 1, start: 1 },
      { note: "G4", duration: 1, start: 2 },
      { note: "G4", duration: 1, start: 3 },
      { note: "A4", duration: 1, start: 4 },
      { note: "A4", duration: 1, start: 5 },
      { note: "G4", duration: 2, start: 6 },
      // Phrase 2: How I wonder what you are
      { note: "F4", duration: 1, start: 8 },
      { note: "F4", duration: 1, start: 9 },
      { note: "E4", duration: 1, start: 10 },
      { note: "E4", duration: 1, start: 11 },
      { note: "D4", duration: 1, start: 12 },
      { note: "D4", duration: 1, start: 13 },
      { note: "C4", duration: 2, start: 14 },
      // Phrase 3: Up above the world so high
      { note: "G4", duration: 1, start: 16 },
      { note: "G4", duration: 1, start: 17 },
      { note: "F4", duration: 1, start: 18 },
      { note: "F4", duration: 1, start: 19 },
      { note: "E4", duration: 1, start: 20 },
      { note: "E4", duration: 1, start: 21 },
      { note: "D4", duration: 2, start: 22 },
      // Phrase 4: Like a diamond in the sky
      { note: "G4", duration: 1, start: 24 },
      { note: "G4", duration: 1, start: 25 },
      { note: "F4", duration: 1, start: 26 },
      { note: "F4", duration: 1, start: 27 },
      { note: "E4", duration: 1, start: 28 },
      { note: "E4", duration: 1, start: 29 },
      { note: "D4", duration: 2, start: 30 },
      // Phrase 5: Twinkle, twinkle, little star (repeat)
      { note: "C4", duration: 1, start: 32 },
      { note: "C4", duration: 1, start: 33 },
      { note: "G4", duration: 1, start: 34 },
      { note: "G4", duration: 1, start: 35 },
      { note: "A4", duration: 1, start: 36 },
      { note: "A4", duration: 1, start: 37 },
      { note: "G4", duration: 2, start: 38 },
      // Phrase 6: How I wonder what you are
      { note: "F4", duration: 1, start: 40 },
      { note: "F4", duration: 1, start: 41 },
      { note: "E4", duration: 1, start: 42 },
      { note: "E4", duration: 1, start: 43 },
      { note: "D4", duration: 1, start: 44 },
      { note: "D4", duration: 1, start: 45 },
      { note: "C4", duration: 2, start: 46 },
    ],
  },
  {
    id: "jingle-bells",
    title: "Jingle Bells",
    artist: "James Lord Pierpont",
    bpm: 120,
    difficulty: "Easy",
    description: "Holiday favourite — chorus only.",
    notes: [
      { note: "E4", duration: 1, start: 0 },
      { note: "E4", duration: 1, start: 1 },
      { note: "E4", duration: 2, start: 2 },
      { note: "E4", duration: 1, start: 4 },
      { note: "E4", duration: 1, start: 5 },
      { note: "E4", duration: 2, start: 6 },
      { note: "E4", duration: 1, start: 8 },
      { note: "G4", duration: 1, start: 9 },
      { note: "C4", duration: 1.5, start: 10 },
      { note: "D4", duration: 0.5, start: 11.5 },
      { note: "E4", duration: 4, start: 12 },
      // F F F F F E E E E E D D E D G
      { note: "F4", duration: 1, start: 16 },
      { note: "F4", duration: 1, start: 17 },
      { note: "F4", duration: 1, start: 18 },
      { note: "F4", duration: 1, start: 19 },
      { note: "F4", duration: 1, start: 20 },
      { note: "E4", duration: 1, start: 21 },
      { note: "E4", duration: 1, start: 22 },
      { note: "E4", duration: 1, start: 23 },
      { note: "E4", duration: 0.5, start: 24 },
      { note: "E4", duration: 0.5, start: 24.5 },
      { note: "E4", duration: 0.5, start: 25 },
      { note: "E4", duration: 0.5, start: 25.5 },
      // D D E D G
      { note: "D4", duration: 1, start: 26 },
      { note: "D4", duration: 1, start: 27 },
      { note: "E4", duration: 1, start: 28 },
      { note: "D4", duration: 1, start: 29 },
      { note: "G4", duration: 2, start: 30 },
      // E E E E E E E G C D E
      { note: "E4", duration: 1, start: 32 },
      { note: "E4", duration: 1, start: 33 },
      { note: "E4", duration: 2, start: 34 },
      { note: "E4", duration: 1, start: 36 },
      { note: "E4", duration: 1, start: 37 },
      { note: "E4", duration: 2, start: 38 },
      { note: "E4", duration: 1, start: 40 },
      { note: "G4", duration: 1, start: 41 },
      { note: "C4", duration: 1.5, start: 42 },
      { note: "D4", duration: 0.5, start: 43.5 },
      { note: "E4", duration: 4, start: 44 },
    ],
  },
  {
    id: "happy-birthday",
    title: "Happy Birthday",
    artist: "Patty & Mildred J. Hill",
    bpm: 100,
    difficulty: "Beginner",
    description: "The world's most-sung song.",
    notes: [
      // "Happy birthday to you"
      { note: "C4", duration: 0.75, start: 0 },
      { note: "C4", duration: 0.25, start: 0.75 },
      { note: "D4", duration: 1, start: 1 },
      { note: "C4", duration: 1, start: 2 },
      { note: "F4", duration: 1, start: 3 },
      { note: "E4", duration: 2, start: 4 },
      // "Happy birthday to you"
      { note: "C4", duration: 0.75, start: 6 },
      { note: "C4", duration: 0.25, start: 6.75 },
      { note: "D4", duration: 1, start: 7 },
      { note: "C4", duration: 1, start: 8 },
      { note: "G4", duration: 1, start: 9 },
      { note: "F4", duration: 2, start: 10 },
      // "Happy birthday dear ___"
      { note: "C4", duration: 0.75, start: 12 },
      { note: "C4", duration: 0.25, start: 12.75 },
      { note: "C5", duration: 1, start: 13 },
      { note: "A4", duration: 1, start: 14 },
      { note: "F4", duration: 1, start: 15 },
      { note: "E4", duration: 1, start: 16 },
      { note: "D4", duration: 2, start: 17 },
      // "Happy birthday to you"
      { note: "B4", duration: 0.75, start: 19 },
      { note: "B4", duration: 0.25, start: 19.75 },
      { note: "A4", duration: 1, start: 20 },
      { note: "F4", duration: 1, start: 21 },
      { note: "G4", duration: 1, start: 22 },
      { note: "F4", duration: 2, start: 23 },
    ],
  },
  {
    id: "mary-lamb",
    title: "Mary Had a Little Lamb",
    artist: "Traditional (Lowell Mason)",
    bpm: 110,
    difficulty: "Beginner",
    description: "First song many children learn — uses just 4 notes.",
    notes: [
      // "Mary had a little lamb"
      { note: "E4", duration: 1, start: 0 },
      { note: "D4", duration: 1, start: 1 },
      { note: "C4", duration: 1, start: 2 },
      { note: "D4", duration: 1, start: 3 },
      { note: "E4", duration: 1, start: 4 },
      { note: "E4", duration: 1, start: 5 },
      { note: "E4", duration: 2, start: 6 },
      // "Little lamb, little lamb"
      { note: "D4", duration: 1, start: 8 },
      { note: "D4", duration: 1, start: 9 },
      { note: "D4", duration: 2, start: 10 },
      { note: "E4", duration: 1, start: 12 },
      { note: "G4", duration: 1, start: 13 },
      { note: "G4", duration: 2, start: 14 },
      // "Mary had a little lamb"
      { note: "E4", duration: 1, start: 16 },
      { note: "D4", duration: 1, start: 17 },
      { note: "C4", duration: 1, start: 18 },
      { note: "D4", duration: 1, start: 19 },
      { note: "E4", duration: 1, start: 20 },
      { note: "E4", duration: 1, start: 21 },
      { note: "E4", duration: 1, start: 22 },
      // "Its fleece was white as snow"
      { note: "D4", duration: 1, start: 24 },
      { note: "D4", duration: 1, start: 25 },
      { note: "E4", duration: 1, start: 26 },
      { note: "D4", duration: 1, start: 27 },
      { note: "C4", duration: 2, start: 28 },
    ],
  },
  {
    id: "when-the-saints",
    title: "When the Saints Go Marching In",
    artist: "Traditional Spiritual",
    bpm: 120,
    difficulty: "Easy",
    description: "A joyful New Orleans jazz standard.",
    notes: [
      { note: "C4", duration: 1, start: 0 },
      { note: "E4", duration: 1, start: 1 },
      { note: "F4", duration: 1, start: 2 },
      { note: "G4", duration: 1, start: 3 },
      { note: "C5", duration: 1, start: 4 },
      { note: "G4", duration: 1, start: 5 },
      { note: "F4", duration: 1, start: 6 },
      { note: "E4", duration: 1, start: 7 },
      { note: "C4", duration: 1, start: 8 },
      { note: "E4", duration: 1, start: 9 },
      { note: "F4", duration: 1, start: 10 },
      { note: "G4", duration: 1, start: 11 },
      { note: "E4", duration: 2, start: 12 },
      // Phrase 2
      { note: "C4", duration: 1, start: 16 },
      { note: "E4", duration: 1, start: 17 },
      { note: "F4", duration: 1, start: 18 },
      { note: "G4", duration: 1, start: 19 },
      { note: "C5", duration: 1, start: 20 },
      { note: "G4", duration: 1, start: 21 },
      { note: "F4", duration: 1, start: 22 },
      { note: "E4", duration: 1, start: 23 },
      { note: "C4", duration: 1, start: 24 },
      { note: "E4", duration: 1, start: 25 },
      { note: "D4", duration: 1, start: 26 },
      { note: "C4", duration: 2, start: 27 },
    ],
  },
  {
    id: "amazing-grace",
    title: "Amazing Grace",
    artist: "John Newton (Traditional)",
    bpm: 90,
    difficulty: "Easy",
    description: "A timeless hymn with a beautiful melody.",
    notes: [
      // "Amazing grace, how sweet the sound"
      { note: "C4", duration: 1.5, start: 0 },
      { note: "E4", duration: 0.5, start: 1.5 },
      { note: "G4", duration: 1, start: 2 },
      { note: "E4", duration: 1, start: 3 },
      { note: "C4", duration: 1, start: 4 },
      { note: "E4", duration: 1, start: 5 },
      { note: "G4", duration: 2, start: 6 },
      // "That saved a wretch like me"
      { note: "E4", duration: 1.5, start: 8 },
      { note: "G4", duration: 0.5, start: 9.5 },
      { note: "C5", duration: 1, start: 10 },
      { note: "B4", duration: 1, start: 11 },
      { note: "G4", duration: 1, start: 12 },
      { note: "E4", duration: 1, start: 13 },
      { note: "C4", duration: 2, start: 14 },
      // "I once was lost, but now am found"
      { note: "D4", duration: 1.5, start: 16 },
      { note: "E4", duration: 0.5, start: 17.5 },
      { note: "G4", duration: 1, start: 18 },
      { note: "E4", duration: 1, start: 19 },
      { note: "C4", duration: 1, start: 20 },
      { note: "D4", duration: 1, start: 21 },
      { note: "E4", duration: 2, start: 22 },
      // "Was blind, but now I see"
      { note: "C4", duration: 1, start: 24 },
      { note: "E4", duration: 1, start: 25 },
      { note: "G4", duration: 1, start: 26 },
      { note: "E4", duration: 1, start: 27 },
      { note: "C4", duration: 3, start: 28 },
    ],
  },
  {
    id: "scarborough-fair",
    title: "Scarborough Fair",
    artist: "Traditional English",
    bpm: 80,
    difficulty: "Intermediate",
    description: "A haunting modal folk ballad popularised by Simon & Garfunkel.",
    notes: [
      // Phrase A — Dorian flavour
      { note: "A4", duration: 1, start: 0 },
      { note: "A4", duration: 0.5, start: 1 },
      { note: "G4", duration: 0.5, start: 1.5 },
      { note: "A4", duration: 1, start: 2 },
      { note: "C5", duration: 1, start: 3 },
      { note: "A4", duration: 1, start: 4 },
      { note: "G4", duration: 1, start: 5 },
      { note: "E4", duration: 2, start: 6 },
      // Phrase B
      { note: "G4", duration: 1, start: 8 },
      { note: "A4", duration: 0.5, start: 9 },
      { note: "G4", duration: 0.5, start: 9.5 },
      { note: "E4", duration: 1, start: 10 },
      { note: "D4", duration: 1, start: 11 },
      { note: "C4", duration: 1, start: 12 },
      { note: "D4", duration: 1, start: 13 },
      { note: "E4", duration: 2, start: 14 },
      // Phrase A repeat
      { note: "A4", duration: 1, start: 16 },
      { note: "A4", duration: 0.5, start: 17 },
      { note: "G4", duration: 0.5, start: 17.5 },
      { note: "A4", duration: 1, start: 18 },
      { note: "C5", duration: 1, start: 19 },
      { note: "A4", duration: 1, start: 20 },
      { note: "G4", duration: 1, start: 21 },
      { note: "E4", duration: 2, start: 22 },
      // Phrase C — close
      { note: "D4", duration: 1, start: 24 },
      { note: "C4", duration: 1, start: 25 },
      { note: "D4", duration: 1, start: 26 },
      { note: "E4", duration: 1, start: 27 },
      { note: "C4", duration: 2, start: 28 },
      { note: "A3", duration: 2, start: 30 },
    ],
  },
  {
    id: "fur-elise",
    title: "Für Elise",
    artist: "Ludwig van Beethoven",
    bpm: 130,
    difficulty: "Intermediate",
    description: "Beethoven's famous Bagatelle No. 25 in A minor — opening theme.",
    notes: [
      // Iconic opening: E D# E D# E B D C A
      { note: "E5", duration: 0.5, start: 0 },
      { note: "D#5", duration: 0.5, start: 0.5 },
      { note: "E5", duration: 0.5, start: 1 },
      { note: "D#5", duration: 0.5, start: 1.5 },
      { note: "E5", duration: 0.5, start: 2 },
      { note: "B4", duration: 0.5, start: 2.5 },
      { note: "D5", duration: 0.5, start: 3 },
      { note: "C5", duration: 0.5, start: 3.5 },
      { note: "A4", duration: 1.5, start: 4 },
      // Phrase 2: C E A B
      { note: "C4", duration: 0.5, start: 5.5 },
      { note: "E4", duration: 0.5, start: 6 },
      { note: "A4", duration: 0.5, start: 6.5 },
      { note: "B4", duration: 1, start: 7 },
      // Phrase 3: E G# B C
      { note: "E4", duration: 0.5, start: 8 },
      { note: "G#4", duration: 0.5, start: 8.5 },
      { note: "B4", duration: 0.5, start: 9 },
      { note: "C5", duration: 1, start: 9.5 },
      // Phrase 4: E D# E D# E B D C A (repeat of opening)
      { note: "E5", duration: 0.5, start: 11 },
      { note: "D#5", duration: 0.5, start: 11.5 },
      { note: "E5", duration: 0.5, start: 12 },
      { note: "D#5", duration: 0.5, start: 12.5 },
      { note: "E5", duration: 0.5, start: 13 },
      { note: "B4", duration: 0.5, start: 13.5 },
      { note: "D5", duration: 0.5, start: 14 },
      { note: "C5", duration: 0.5, start: 14.5 },
      { note: "A4", duration: 2, start: 15 },
    ],
  },
  {
    id: "ode-to-joy",
    title: "Ode to Joy",
    artist: "Ludwig van Beethoven",
    bpm: 110,
    difficulty: "Easy",
    description: "Beethoven's Ninth Symphony, fourth movement theme.",
    notes: [
      { note: "E4", duration: 1, start: 0 },
      { note: "E4", duration: 1, start: 1 },
      { note: "F4", duration: 1, start: 2 },
      { note: "G4", duration: 1, start: 3 },
      { note: "G4", duration: 1, start: 4 },
      { note: "F4", duration: 1, start: 5 },
      { note: "E4", duration: 1, start: 6 },
      { note: "D4", duration: 1, start: 7 },
      { note: "C4", duration: 1, start: 8 },
      { note: "C4", duration: 1, start: 9 },
      { note: "D4", duration: 1, start: 10 },
      { note: "E4", duration: 1, start: 11 },
      { note: "E4", duration: 1.5, start: 12 },
      { note: "D4", duration: 0.5, start: 13.5 },
      { note: "D4", duration: 2, start: 14 },
      { note: "E4", duration: 1, start: 16 },
      { note: "E4", duration: 1, start: 17 },
      { note: "F4", duration: 1, start: 18 },
      { note: "G4", duration: 1, start: 19 },
      { note: "G4", duration: 1, start: 20 },
      { note: "F4", duration: 1, start: 21 },
      { note: "E4", duration: 1, start: 22 },
      { note: "D4", duration: 1, start: 23 },
      { note: "C4", duration: 1, start: 24 },
      { note: "C4", duration: 1, start: 25 },
      { note: "D4", duration: 1, start: 26 },
      { note: "E4", duration: 1, start: 27 },
      { note: "D4", duration: 1.5, start: 28 },
      { note: "C4", duration: 0.5, start: 29.5 },
      { note: "C4", duration: 2, start: 30 },
    ],
  },
];

/** Convenience lookup by id. */
export function findSongById(id: string): Song | undefined {
  return SONGS.find((s) => s.id === id);
}

/** Total song length in beats (last note start + duration). */
export function songLengthBeats(song: Song): number {
  return song.notes.reduce((max, n) => Math.max(max, n.start + n.duration), 0);
}

/** Convert a beat count to seconds at a given BPM (no tempo multiplier). */
export function beatsToSeconds(beats: number, bpm: number): number {
  return (beats * 60) / bpm;
}
